services:
  arangodb:
    image: arangodb:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    environment:
      ARANGO_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - ${HOST_IP}:${PORT}:5829
    volumes:
      - ${APP_PATH}/data/primary:/data/db
    networks:
      - baota_net

networks:
  baota_net:
    external: true